title: "関数型プログラミングをPythonで実践しよう"
summary: "本書は、Pythonを使って関数型プログラミングを実践するためのガイドブックです。関数型プログラミングの基本的な概念を整理し、それをPythonのプログラミングにどのように応用できるかを示します。さらに、Pythonの型付けを使ったプログラムの堅牢性の向上や、関数型プログラミングに特化した単体テストの方法も取り上げます。関数型思考をPythonで実現し、コードをより効率的に、読みやすく保つための実践的な知識を整理することが本書の目的です。"
topics: [Python, 関数型プログラミング]
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - fp_with_openai_api_call
  # - introduce_typing
  # - unit_testing
  # - afterword
  - references